In [2]:
import pandas as pd

In [4]:
pd.read_csv('course_offerings.csv') # in the same folder as JN - just write file name

   course_id                  course_name    instructor
0        101              Intro to Python  Chris Bruehl
1        102                 Intro to SQL   John Pauler
2        201    Exploratory Data Analysis    Alice Zhao
3        301                   Algorithms  Chris Bruehl
4        331  Natural Language Processing    Alice Zhao

In [5]:
pd.read_csv('/Users/alinaaleks/Downloads/GitHub/maven-data-science-path/01-data-prep-eda/course_offerings.csv') # writing exact path

   course_id                  course_name    instructor
0        101              Intro to Python  Chris Bruehl
1        102                 Intro to SQL   John Pauler
2        201    Exploratory Data Analysis    Alice Zhao
3        301                   Algorithms  Chris Bruehl
4        331  Natural Language Processing    Alice Zhao

In [6]:
pd.read_csv('data/course_offerings_below.csv') # relative path

   course_id                  course_name    instructor
0        101              Intro to Python  Chris Bruehl
1        102                 Intro to SQL   John Pauler
2        201    Exploratory Data Analysis    Alice Zhao
3        301                   Algorithms  Chris Bruehl
4        331  Natural Language Processing    Alice Zhao

In [7]:
pd.read_csv('../data/course_offerings_above.csv') # relative path if the folder is higher

   course_id                  course_name    instructor
0        101              Intro to Python  Chris Bruehl
1        102                 Intro to SQL   John Pauler
2        201    Exploratory Data Analysis    Alice Zhao
3        301                   Algorithms  Chris Bruehl
4        331  Natural Language Processing    Alice Zhao

In [14]:
pd.read_csv('course_offerings.csv') # (Shift + Tab => open settings)

   course_id                  course_name    instructor
0        101              Intro to Python  Chris Bruehl
1        102                 Intro to SQL   John Pauler
2        201    Exploratory Data Analysis    Alice Zhao
3        301                   Algorithms  Chris Bruehl
4        331  Natural Language Processing    Alice Zhao

In [18]:
pd.read_csv('course_offerings.csv', sep=',') # specify separator

   course_id                  course_name    instructor
0        101              Intro to Python  Chris Bruehl
1        102                 Intro to SQL   John Pauler
2        201    Exploratory Data Analysis    Alice Zhao
3        301                   Algorithms  Chris Bruehl
4        331  Natural Language Processing    Alice Zhao

In [21]:
pd.read_csv('course_offerings.csv', sep=',', header=None)

           0                            1             2
0  course_id                  course_name    instructor
1        101              Intro to Python  Chris Bruehl
2        102                 Intro to SQL   John Pauler
3        201    Exploratory Data Analysis    Alice Zhao
4        301                   Algorithms  Chris Bruehl
5        331  Natural Language Processing    Alice Zhao

In [26]:
pd.read_excel('Course Offerings.xlsx', sheet_name=1) # sheets start count from 0

   Course ID                  Course Name    Instructor
0        101              Intro to Python  Chris Bruehl
1        102                 Intro to SQL   John Pauler
2        201    Exploratory Data Analysis    Alice Zhao
3        301                   Algorithms  Chris Bruehl
4        331  Natural Language Processing    Alice Zhao

In [31]:
import sqlite3 # connect to SQL DB

In [32]:
conn = sqlite3.connect('../data/maven.db')

In [33]:
pd.read_sql('SELECT * FROM courses', conn)

   course_id                       course    instructor
0        101              Intro to Python  Chris Bruehl
1        102                 Intro to SQL   John Pauler
2        201    Exploratory Data Analysis    Alice Zhao
3        301                   Algorithms  Chris Bruehl
4        331  Natural Language Processing    Alice Zhao

In [34]:
pd.read_sql('SELECT * FROM courses WHERE course_id=101', conn)

   course_id           course    instructor
0        101  Intro to Python  Chris Bruehl

In [35]:
pd.read_sql('SELECT * FROM courses WHERE course_id LIKE "1%"', conn)

   course_id           course    instructor
0        101  Intro to Python  Chris Bruehl
1        102     Intro to SQL   John Pauler

#### install a db driver (pip install or conda install):

In [37]:
!pip install mysql-connector-python

Collecting mysql-connector-python
  Downloading mysql_connector_python-9.6.0-cp311-cp311-win_amd64.whl.metadata (11 kB)
Downloading mysql_connector_python-9.6.0-cp311-cp311-win_amd64.whl (16.5 MB)
   ---------------------------------------- 0.0/16.5 MB ? eta -:--:--
   - -------------------------------------- 0.5/16.5 MB 3.4 MB/s eta 0:00:05
   -- ------------------------------------- 1.0/16.5 MB 2.8 MB/s eta 0:00:06
   --- ------------------------------------ 1.6/16.5 MB 2.8 MB/s eta 0:00:06
   ----- ---------------------------------- 2.1/16.5 MB 2.8 MB/s eta 0:00:06
   ------ --------------------------------- 2.9/16.5 MB 2.8 MB/s eta 0:00:05
   -------- ------------------------------- 3.7/16.5 MB 2.9 MB/s eta 0:00:05
   ---------- ----------------------------- 4.2/16.5 MB 3.0 MB/s eta 0:00:05
   ------------ --------------------------- 5.0/16.5 MB 3.0 MB/s eta 0:00:04
   ------------- -------------------------- 5.8/16.5 MB 3.1 MB/s eta 0:00:04
   --------------- ------------------------ 6.6/16.5 MB 3.1 MB/s eta 0:00:04
   ----------------- ---------------------- 7.3/16.5 MB 3.2 MB/s eta 0:00:03
   ------------------- -------------------- 8.1/16.5 MB 3.2 MB/s eta 0:00:03
   -------------------- ------------------- 8.7/16.5 MB 3.2 MB/s eta 0:00:03
   ---------------------- ----------------- 9.2/16.5 MB 3.2 MB/s eta 0:00:03
   ----------------------- ---------------- 9.7/16.5 MB 3.1 MB/s eta 0:00:03
   ------------------------ --------------- 10.0/16.5 MB 3.1 MB/s eta 0:00:03
   ------------------------ --------------- 10.0/16.5 MB 3.1 MB/s eta 0:00:03
   -------------------------- ------------- 10.7/16.5 MB 2.8 MB/s eta 0:00:03
   --------------------------- ------------ 11.3/16.5 MB 2.8 MB/s eta 0:00:02
   ----------------------------- ---------- 12.1/16.5 MB 2.9 MB/s eta 0:00:02
   ------------------------------- -------- 12.8/16.5 MB 2.9 MB/s eta 0:00:02
   --------------------------------- ------ 13.6/16.5 MB 2.9 MB/s eta 0:00:01
   --------------------------------- ------ 13.6/16.5 MB 2.9 MB/s eta 0:00:01
   ------------------------------------ --- 14.9/16.5 MB 3.0 MB/s eta 0:00:01
   ------------------------------------- -- 15.5/16.5 MB 2.9 MB/s eta 0:00:01
   ---------------------------------------  16.3/16.5 MB 2.9 MB/s eta 0:00:01
   ---------------------------------------- 16.5/16.5 MB 2.9 MB/s  0:00:05
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-9.6.0

In [39]:
import mysql.connector

In [49]:
# MySQL connection
conn = mysql.connector.connect(host='localhost',
                               database='mavenmovies',
                               user='root',
                               password='password') # insert my pass here

ProgrammingError: 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)

In [42]:
pd.read_sql('SELECT * FROM city', conn)

C:\Users\alinaaleks\AppData\Local\Temp\ipykernel_8484\2964174485.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql('SELECT * FROM city', conn)

     city_id                city  country_id         last_update
0          1  A Corua (La Corua)          87 2006-02-15 04:45:25
1          2                Abha          82 2006-02-15 04:45:25
2          3           Abu Dhabi         101 2006-02-15 04:45:25
3          4                Acua          60 2006-02-15 04:45:25
4          5               Adana          97 2006-02-15 04:45:25
..       ...                 ...         ...                 ...
595      596               Zaria          69 2006-02-15 04:45:25
596      597        Zeleznogorsk          80 2006-02-15 04:45:25
597      598         Zhezqazghan          51 2006-02-15 04:45:25
598      599            Zhoushan          23 2006-02-15 04:45:25
599      600          Ziguinchor          83 2006-02-15 04:45:25

[600 rows x 4 columns]

In [43]:
import psycopg2

In [47]:
# PostgreSQL connection
conn = psycopg2.connect(host='localhost',
                        port=5432,
                        database='parchAndPosey',
                        user='postgres',
                        password='2951620') # insert my pass here

In [48]:
pd.read_sql('SELECT * FROM accounts', conn)

C:\Users\alinaaleks\AppData\Local\Temp\ipykernel_8484\2073245136.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql('SELECT * FROM accounts', conn)

,id,name,website,lat,long,primary_poc,sales_rep_id
0,1001,Walmart,www.walmart.com,40.238496,-75.103297,Tamara Tuma,321500
1,1011,Exxon Mobil,www.exxonmobil.com,41.169156,-73.849374,Sung Shields,321510
2,1021,Apple,www.apple.com,42.290495,-76.084009,Jodee Lupo,321520
3,1031,Berkshire Hathaway,www.berkshirehathaway.com,40.949021,-75.763898,Serafina Banda,321530
4,1041,McKesson,www.mckesson.com,42.217093,-75.284998,Angeles Crusoe,321540
...,...,...,...,...,...,...,...
346,4461,KKR,www.kkr.com,45.545353,-122.655247,Buffy Azure,321970
347,4471,Oneok,www.oneok.com,45.513513,-122.681500,Esta Engelhardt,321960
348,4481,Newmont Mining,www.newmont.com,45.494117,-122.669460,Khadijah Riemann,321970
349,4491,PPL,www.pplweb.com,45.491720,-122.671880,Deanne Hertlein,321960
350,4501,SpartanNash,www.spartannash.com,45.555651,-122.657145,Jewell Likes,321970

In [50]:
from sqlalchemy import create_engine

In [53]:
engine = create_engine('postgresql+psycopg2://postgres:password@localhost:5432/dvdrental')

In [54]:
df = pd.read_sql('SELECT * FROM actor', engine)
print(df)

     actor_id first_name     last_name             last_update
0           1   Penelope       Guiness 2013-05-26 14:47:57.620
1           2       Nick      Wahlberg 2013-05-26 14:47:57.620
2           3         Ed         Chase 2013-05-26 14:47:57.620
3           4   Jennifer         Davis 2013-05-26 14:47:57.620
4           5     Johnny  Lollobrigida 2013-05-26 14:47:57.620
..        ...        ...           ...                     ...
195       196       Bela        Walken 2013-05-26 14:47:57.620
196       197      Reese          West 2013-05-26 14:47:57.620
197       198       Mary        Keitel 2013-05-26 14:47:57.620
198       199      Julia       Fawcett 2013-05-26 14:47:57.620
199       200      Thora        Temple 2013-05-26 14:47:57.620

[200 rows x 4 columns]

In [55]:
df

     actor_id first_name     last_name             last_update
0           1   Penelope       Guiness 2013-05-26 14:47:57.620
1           2       Nick      Wahlberg 2013-05-26 14:47:57.620
2           3         Ed         Chase 2013-05-26 14:47:57.620
3           4   Jennifer         Davis 2013-05-26 14:47:57.620
4           5     Johnny  Lollobrigida 2013-05-26 14:47:57.620
..        ...        ...           ...                     ...
195       196       Bela        Walken 2013-05-26 14:47:57.620
196       197      Reese          West 2013-05-26 14:47:57.620
197       198       Mary        Keitel 2013-05-26 14:47:57.620
198       199      Julia       Fawcett 2013-05-26 14:47:57.620
199       200      Thora        Temple 2013-05-26 14:47:57.620

[200 rows x 4 columns]

In [56]:
df.head()

   actor_id first_name     last_name             last_update
0         1   Penelope       Guiness 2013-05-26 14:47:57.620
1         2       Nick      Wahlberg 2013-05-26 14:47:57.620
2         3         Ed         Chase 2013-05-26 14:47:57.620
3         4   Jennifer         Davis 2013-05-26 14:47:57.620
4         5     Johnny  Lollobrigida 2013-05-26 14:47:57.620

In [57]:
df.head(2)

   actor_id first_name last_name             last_update
0         1   Penelope   Guiness 2013-05-26 14:47:57.620
1         2       Nick  Wahlberg 2013-05-26 14:47:57.620

In [58]:
df.tail(2)

     actor_id first_name last_name             last_update
198       199      Julia   Fawcett 2013-05-26 14:47:57.620
199       200      Thora    Temple 2013-05-26 14:47:57.620

In [59]:
df.shape

(200, 4)

In [60]:
df.count()

actor_id       200
first_name     200
last_name      200
last_update    200
dtype: int64

In [61]:
df.describe()

         actor_id                 last_update
count  200.000000                         200
mean   100.500000  2013-05-26 14:47:57.620000
min      1.000000  2013-05-26 14:47:57.620000
25%     50.750000  2013-05-26 14:47:57.620000
50%    100.500000  2013-05-26 14:47:57.620000
75%    150.250000  2013-05-26 14:47:57.620000
max    200.000000  2013-05-26 14:47:57.620000
std     57.879185                         NaN

In [62]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   actor_id     200 non-null    int64
 1   first_name   200 non-null    str
 2   last_name    200 non-null    str
 3   last_update  200 non-null    datetime64[us]
dtypes: datetime64[us](1), int64(1), str(2)
memory usage: 6.4 KB